# Use the official Node.js image from the Docker Hub
FROM node:latest

# Set the working directory in the container
WORKDIR /app/frontend/

# Install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Build the React application
# RUN npm run build

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the React application
# CMD ["npm", "start"]
