global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'osm-tile-server'
    static_configs:
      - targets: ['osm-tile-server:80']
