# Generated by Django 5.0.7 on 2024-08-13 05:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="Specified Name",
                        max_length=50,
                        verbose_name="Category Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("oldname", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "wkb_geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "db_table": "Cities_India",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                (
                    "gps_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="place_images/"),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "point_geom",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="p1backend.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Places",
            },
        ),
    ]
