version: '3.8'
services:
  debug:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    command: sleep infinity
    
  # Define other services if needed, or override existing services

 
