version: '3.8'

services:
  debug:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 forwarding
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    command: sleep infinity


 
