version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=securepassword
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - common_network

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - common_network

  firefox:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
    networks:
      - common_network

networks:
  common_network:
    driver: bridge


 
